# Generated by Django 4.0.3 on 2022-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_supplier_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
